volumes:
  projeto_extensao_local_postgres_data: {}
  projeto_extensao_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: projeto_extensao_local_django
    container_name: projeto_extensao_local_django
    user: "dev-user"
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: docker.io/postgres:16
    container_name: projeto_extensao_local_postgres
    volumes:
      - projeto_extensao_local_postgres_data:/var/lib/postgresql/data
      - projeto_extensao_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
